### PR TITLE
Translations of strings

### PR DESCRIPTION
**Pull request by kartikarora**
Hindi translations of `strings.xml`, for #8

### CODE REVIEW

**Comment by gsantner** [comment]
thx!

**Comment by gsantner** [comment]
Thanks for translating! As none of my projects but this are available in Hindi yet: Feel free to translate them too, that helps a lot :)

Especially MemeTastic and Markor would fit good with hindi too 😀

**Comment by kartikarora** [comment]
Haha, sure! Will do! Can I add `hacktoberfest` to those PRs?

**Comment by gsantner** [comment]
In all of my projects there are translation issues like this one with the tag

**Comment by kartikarora** [comment]
Great! I'll work on them!

**Comment by gsantner** [comment]
Nice :D 
I am happy about any Asian language support, currently mostly only Russian and Japanese is supported. Chinese (simpl,trad), Indian, Taiwanese is mostly not done

**Comment by kartikarora** [comment]
Haha, Indian is not a language. Infact, India has a lot of languages! I know Hindi, will be able to translate to that! :smile:

**Comment by gsantner** [comment]
Yeah, but in India a set of languages are spoken right, Hindi, Bengali, Sindhi

**Comment by gsantner** [comment]
How big is the population talking `Malayalam`? Thats the only indian language that is translated in some of my foss projects

**Comment by kartikarora** [comment]
Yup. A lot of them. As per the census of 2001, around 122 main languages and 1599 dialects.

Malayalam is a major language here. [These](https://en.wikipedia.org/wiki/Languages_of_India#Prominent_languages_of_India) are some of the major languages in India. Along with English, which is used all over India.

**Comment by gsantner** [comment]
Oh, yeah, Kannada is too supported by froody and dandelion :D

**Comment by gsantner** [comment]
Modified the icon text a little, so it's more like what I meant, first one may had a different meaning

**Comment by kartikarora** [comment]
Didn't get you @gsantner

**Comment by gsantner** [comment]
on memetastic, ups, wrong issue comment :D

**Pull request merged**
