### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by Poussinou**
notify me in the future if there is any new key to translate or to change ;)

### CODE REVIEW

**Comment by gsantner** [comment]
Hi there, thank you very much!
I will do!

I cannot merge your changes because there are errors in it, please correct:
* Remove all lines marked as translatable=false
* Line 42 has a bad string closing tag

**Comment by Poussinou** [comment]
Sorry about the line 42

I will remove all the translatable=false keys in the other future translations I'll do (I prefer to have them as a translator since it give some context, that helps^^)

**Comment by gsantner** [comment]
no problem

In general (also in other apps): Don't do translate those entries marked as not-translatable. It also won't give you any information of other strings, the order and the keys are per se not related. It's better to ask devs what this is about, or convience them to add comments :D.

Thank you for your translations! Merging now.

**Comment by Poussinou** [comment]
OK thanks ;)

**Comment by gsantner** [comment]
@Poussinou 
I will change license of translation files to Creative Commons Zero (CC0 1.0), as in all other of my FOSS android app projects. Are you okay with that?

**Pull request merged**
