### PR TITLE
Fix Link To F-Droid And Add Google Play Badge

### PR DESCRIPTION
**Pull request by Sylvia-Keren-Happuch**

### CODE REVIEW

**Comment by gsantner** [comment]
@Sylvia-Keren-Happuch 
Sorry, but I cannot merge the F-Droid part. The link doesn't work with the legacy version (/the version with old design), and I want to stay compatible with it for now. Change to current version

**Comment by Sylvia-Keren-Happuch** [comment]
What do you mean with the current version? The link who is used in the Readme now (https://f-droid.org/repository/browse/?fdfilter=kimai&fdid=de.live.gdev.timetracker) gives a 404 here.

**Comment by gsantner** [comment]
https://f-droid.org/repository/browse/?fdid=de.live.gdev.timetracker

works for me on new & old app, and web aswell

**Comment by Sylvia-Keren-Happuch** [comment]
Ah, I see. https://f-droid.org/repository/browse/?fdid=de.live.gdev.timetracker is working 👌

**Pull request merged**
